# General experiment parameters
exp_config_name: "german_experiments5"
dataset: "german"
sensitive_attrs_for_intervention: ["sex"]
null_imputers: ["miss_forest"]
fairness_interventions: ["DIR"]
models: ["dt_clf", "lr_clf"]
#random_state: 42
#num_runs: 2
run_nums: [1, 2]
secrets_path: "/Users/denys_herasymuk/Research/NYU/VirnyFlow_Project/Code/virny-flow/virny_flow_demo/configs/secrets.env"

# Parameters for optimisation
ref_point: [0.20, 0.10]
objectives:
  - { name: "objective_1", metric: "F1", group: "overall", weight: 0.25 }
  - { name: "objective_2", metric: "Equalized_Odds_TPR", group: "sex", weight: 0.75 }
max_trials: 5
num_workers: 4
num_pp_candidates: 2
training_set_fractions_for_halting: [0.5, 0.75, 1.0]
exploration_factor: 0.5
risk_factor: 0.5
